version: '3' 

services:

  proxy:
    image: alexanderkrause/rpi-nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: anki-proxy
    networks:
      - anki_network
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
    container_name: anki-letsencrypt
    depends_on:
      - proxy
    networks:
      - anki_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  
  app:
    build: docker-anki-sync-server/Docker
    container_name: anki-server
    networks:
      - anki_network
    depends_on:
      - letsencrypt
      - proxy
    ports:
      - 80:27701
    volumes:
      - /home/pi/anki/anki-data:/app/data:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - anki-variables.env
    restart: unless-stopped

networks:
  anki_network:
